### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Alexy1113** [Sh3llcod3/Airscript-ng#5] opened 2020-12-02 16:15 UTC
bin/sh: 1: /root/.airscriptNG/air/*/src/airodump-ng: not found
![Screenshot from 2020-12-02 16-15-30](https://user-images.githubusercontent.com/75134824/100899335-9fd40b00-34b9-11eb-8891-7dc11727967d.png)

[
![Screenshot from 2020-12-02 16-14-30](https://user-images.githubusercontent.com/75134824/100899242-8206a600-34b9-11eb-9a74-93abceed7f6c.png)
](url)

**Comment by Sh3llcod3** [comment] 2021-01-21 19:26
@Alexy1113 Thanks for the issue, sorry I've been away, I'll take a look and fix it.

**Comment by Sh3llcod3** [comment] 2021-01-21 19:30
I think the issue is that airmon-ng isn't marked as executable, so doing `chmod +x path/shown/on/error` should fix the problem temporarily.

**Comment by Nicholas55555** [comment] 2021-08-15 04:21
Uninstall all of the dependencies and reinstall them with github (option 7)        

Now I have this bug: /bin/sh: 1: /root/.airscriptNG/air/aircrack-ng/src/airodump-ng: Permission denied   

 but hey, at least its installed.

**Comment by Sh3llcod3** [comment] 2021-08-15 13:38
Closed due to suggested fix #dev branch already has new system for installing deps.

**Closed** 2021-08-15 13:38 UTC
Labels: bug
